ナビバーの実装
yanbaru-expert/team_project_55 pull request #35
Opened 2021-07-04 15:02 UTC by TakehiroKatayama

close #11

## 実装内容

- Bootstrap のナビバーを利用して，ナビバーを作成
  - app/views/layouts/_header.html.erb を編集
  - .fixed-top を使用して上に固定
  - ロゴは app/assets/images/yanbaru_expert_logo.png を利用
  - リンクは link_to ヘルパーメソッドを使用
  - PHPテキスト教材のパスは texts_path(genre: "php"), 動画教材は movies_path(genre: "php") とする
  - md サイズ未満で「ハンバーガーメニュー」に切り替わるようにする

- コンテンツがヘッダーに隠れないように調整
  -  body タグに padding-top を設定

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2021-07-05 03:05 UTC, great084 requested changes
@TakehiroKatayama 

- ローカルでrailsサーバ起動しましたが、エラーとなりました確認ください。(動作確認できている状況でプルリク出していますか？）
 
```
ActionView::Template::Error (Error: File to import not found or unreadable: @fortawesome/fontawesome-free/scss/fontawesome.
        on line 8:1 of app/assets/stylesheets/application.scss
>> @import '@fortawesome/fontawesome-free/scss/fontawesome';

   ^
):
     5:     <meta name="viewport" content="width=device-width,initial-scale=1">
     6:     <%= csrf_meta_tags %>
     7:     <%= csp_meta_tag %>
     8:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     9:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    10:   </head>
    11:   <body>
```

- ナビバーの表示だけであれば不要だと思いますが、Fontawesomeはなんのためにインストールしたのでしょうか？

2021-07-05 12:40 UTC, TakehiroKatayama commented
@great084 

- Railsサーバーをローカル環境で起動し動作確認を行っておりましたが、そのようなエラーが発生しませんでした。
(ターミナルにて`rails server`を入力しブラウザにて動作確認を行いました。)

- 当初、Fontawesomeを使用すると考えましたが結果的に使用しなかったためにインストールした状態となっておりました。

- エラー文ではFontawesomeをインストールしているが使用せずにインポートを行なっているために発生しているエラーと考えます。
対処法としては以下の手順を考えておりますがよろしいでしょうか？

  - Fontawesomeをアンインストールしインポートの記述を削除
    `$ yarn remove @fortawesome/fontawesome-free`

  - `app/javascript/packs/application.js` `app/assets/stylesheets/application.scss`インポートの記述を削除

2021-07-06 14:25 UTC, great084 commented
@TakehiroKatayama 

回答ありがとうございます。
使用しないということであれば、アンインストールしてください。

2021-07-06 14:40 UTC, great084 approved these changes
LGTM!

2021-07-06 14:40 UTC, TakehiroKatayama commented
@great084 
ご回答頂きありがとうございます。
修正致しましたので再度、レビューの程よろしくお願い致します。

2021-07-06 15:02 UTC, merged