動画教材の読破済み機能実装
yanbaru-expert/team_project_55 pull request #48
Opened 2021-08-15 01:36 UTC by Orizin-code

対応するissue #23

## 実装内容
- 視聴済み機能に使用する `WatchProgress` モデルを作成
  - 外部キー設定を行い，ユニーク制約を入れてからマイグレーション
  - バリデーションをモデルに追加
  - 関連付けを入れる

- 動画教材一覧ページに視聴済み機能を実装
  - 非同期で処理できるようにすること

## 動作確認
- 以下を確認
```rb
rails c -s

# Railsコンソール起動後
user = User.first
movie, movie2 = Movie.limit(2)
WatchProgress.delete_all

user.watch_progresses.create!(movie_id: movie.id)
user.watch_progresses.create!(movie_id: movie2.id)

WatchProgress.count
#=> 2

movie.watch_progresses.create!(user_id: user.id)

WatchProgress.create!
```

- 動画教材一覧ページの視聴済み機能が動作していることを確認

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2021-08-15 13:50 UTC, motokin128 approved these changes
LGTM です

2021-08-15 15:33 UTC, great084 requested changes

2021-08-15 15:33 UTC, great084 commented on app/views/movies/_unwatch.html.erb
> +<%= link_to "読破済みにする", movie_watch_progresses_path(movie), method: :post, remote: true, class: "btn btn-secondary btn-block" %>
"読破済みにする" ではなく、"視聴済みにする"ですね。
他も同様。

2021-08-16 00:49 UTC, Orizin-code commented
## 実装内容
- 軽微な文言を修正

レビューよろしくお願いいたします！

2021-08-18 23:48 UTC, great084 approved these changes
LGTMです！

2021-08-19 13:49 UTC, merged